### PR TITLE
Add context text field value (if any) on faceted view

### PR DESCRIPTION
**Pull request by laulaz**
The text is located after content description & before faceted filters widgets.
Example usages: OOTB collection text field, plone.richtext behavior

This refs eea/eea.facetednavigation#230

### CODE REVIEW

**Comment by laulaz** [comment]
@avoinea could you please take a look at this ?  🙏

**Comment by laulaz** [comment]
or maybe someone else? @alecghica @ichim-david maybe 😉

**Comment by laulaz** [comment]
@avoinea any news on this ?  🙏

**Comment by avoinea** [comment]
Nope. Holiday time! 😅😎🌴

**Comment by avoinea** [comment]
@laulaz Wouldn't it be more useful to create another widget type like the portlet one called **Metadata**?

This way one could render any context metadata and move it anywhere within the page.

**By the way:**

You can already accomplish the behavior proposed by this PR by adding a template anywhere within the code (by registering a custom browser view) or via **portal_skins/custom** called **render_text** with code:

```
<div metal:define-macro="text" tal:define="text here/getText" tal:condition="text">
  <div tal:replace="structure text">The body</div>
</div>

```

Then add a `Plone portlet` facet with **Portlet macro** = `here/render_text/macros/text`

[faceted-text-portlet.webm](https://user-images.githubusercontent.com/323385/179943895-71402833-8864-4224-9b9d-999c7ae98193.webm)

**Pull request closed without merging**
