### PR TITLE
Plone5 protect

### PR DESCRIPTION
**Pull request by bloodbare**
I don't know what are your plans for further plone 5 (cutting a version for it), just solved some minor problems so it runs on plone 5.

### CODE REVIEW

**Comment by avoinea** [comment]
@bloodbare Please re-submit this pull request within [collective/eea.facetednavigation](https://github.com/collective/eea.facetednavigation). See [CONTRIBUTING.md](https://github.com/collective/eea.facetednavigation/blob/master/CONTRIBUTING.md).

Thank you!

**Comment by avoinea** [comment]
@bloodbare Can't merge as Travis-CI has some complains about this :)

**Comment by avoinea** [comment]
```
  File "/home/travis/build/eea/eea.facetednavigation/eea/facetednavigation/browser/app/view.py", line 14, in <module>
    from Products.CMFPlone.resources import add_bundle_on_request
ZopeXMLConfigurationError: File "/home/travis/build/eea/eea.facetednavigation/buildouts/plone4/eggs/Zope2-2.13.22-py2.7.egg/Zope2/utilities/skel/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/home/travis/build/eea/eea.facetednavigation/buildouts/plone4/eggs/Products.CMFPlone-4.3.6-py2.7.egg/Products/CMFPlone/configure.zcml", line 98.4-102.10
    ZopeXMLConfigurationError: File "/home/travis/build/eea/eea.facetednavigation/eea/facetednavigation/configure.zcml", line 8.2-8.33
    ZopeXMLConfigurationError: File "/home/travis/build/eea/eea.facetednavigation/eea/facetednavigation/minimal.zcml", line 22.2-22.32
    ZopeXMLConfigurationError: File "/home/travis/build/eea/eea.facetednavigation/eea/facetednavigation/browser/configure.zcml", line 9.2-15.6
    ImportError: No module named resources
```

**Comment by bloodbare** [comment]
Yes, sorrry I didn't try catch the import to know if weare in plone 5, are
you planning to maintain this package 4.3 and 5 at the same time ?

El dt., 6 oct. 2015 a les 9:32, Alin Voinea (<notifications@github.com>) va
escriure:

**Comment by avoinea** [comment]
Yap. At least for a while.

**Pull request closed without merging**
