### PR TITLE
202 gs purge criterion

### PR DESCRIPTION
**Pull request by gbastien**
This also include #204 fix...

Will adapt things before merge.

Thank you,

Gauthier

### CODE REVIEW

**Comment by avoinea** [comment]
@gbastien Thank you! 

Can you please rebase this PR branch on `eea:develop` to make the tests pass.

**Comment by gbastien** [comment]
Hi @avoinea done, could you please review and merge?
Thank you!
Gauthier

**Comment by avoinea** [comment]
@gbastien I don't see the xml where do you purge at criterion level. Do I miss something?

**Comment by gbastien** [comment]
Hi @avoinea 

I fixed the test, I was disturbed during write of this test by doctests never failing ;-)

This time this should be done, to use "purge" at <criterion> level, purge="False" must be set at <criteria> level as it is purge="True" by default.

Gauthier

**Review by avoinea — APPROVED** [review]

**Comment by gbastien** [comment]
@avoinea Great!

I would like to propose another PR regarding #207 so feel free to make a new release when you want or not ;-)

Gauthier

**Comment by gbastien** [comment]
Hi @avoinea 

finally as #207 will take a bit longer than expected, I think we can go on discussing it and precising the use case but we have urgent work to do on another thing for now.

So if you could do a new release that would be great ;-)

Thank you!

Gauthier

**Pull request merged**
