### PR TITLE
Community: Select / Multiselect features and bug fixes

### PR DESCRIPTION
**Pull request by avoinea**

### CODE REVIEW

**Comment by avoinea** [comment]
@laulaz Could you please provide a use case where you need to remove "All" option. Because removing that from select will end-up in view mode with first option selected.

**Comment by laulaz** [comment]
> @laulaz Could you please provide a use case where you need to remove "All" option. Because removing that from select will end-up in view mode with first option selected.

@avoinea this is exactly our use case 😄, as we needed a select where : 
- you cannot choose more than one value
- the first value is used as default (if none selected)

Our use case is a list of meeting dates, where you can only search inside one meeting at a time.

We can keep it in a custom widget if you think that this is not generic enough ...

**Comment by avoinea** [comment]
> We can keep it in a custom widget if you think that this is not generic enough ...

No, it's ok as long as you can enable/disable it. 

Another use case I can think of, would be to have a vocabulary with "All" option already predefined, thus avoid duplicates.

**Comment by laulaz** [comment]
@avoinea any idea when this will be merged & released ?

Thank you very much for your reactivity !

**Comment by laulaz** [comment]
@alecghica @avoinea #188 should be merged too (to fix reset of select widget).

**Pull request merged**
