### PR TITLE
Fixed MANIFEST.in

### PR DESCRIPTION
**Pull request by mauritsvanrees**
I don't know how the previous releases were done correctly, maybe with the setuptools_git package.
But this pull request fixes the manifest so everything is included without needing extra setuptools helper packages.
I recommend installing `zest.releaser[recommended]` to release packages. The recommended packages contain check-manifest, which I used for checking the manifest.

And it includes pyroma, which checks the setup.py. Following its recommendations, I added a few classifiers to setup.py.

BTW, maybe make a new release? :)

### CODE REVIEW

**Comment by avoinea** [comment]
@mauritsvanrees please also drop a line about this within docs/HISTORY.txt.

Thank you.

**Comment by mauritsvanrees** [comment]
I usually don't add history lines for such small changes, but if you appreciate it, I am happy to. :-) Done.

BTW, in the history under release 7.3 I see "Add Plone 5 support and move Plone 4 support into a BBB profile."  But in the `buildouts` directory I only see a plone3 and plone4 directory. Travis only tests Plone 4. So I am not sure if Plone 5 is currently really supported. Therefore I have not added it to the classifiers in setup.py.

**Comment by avoinea** [comment]
Unfortunately I had to remove **setup.cfg** as it's incompatible with [eea.eggmonkey](https://pypi.python.org/pypi/eea.eggmonkey) releaser, the tool we currently use to release all EEA eggs.

<pre>
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    """
  File "/usr/lib/python2.7/distutils/core.py", line 124, in setup
    dist.parse_config_files()
  File "/usr/lib/python2.7/distutils/dist.py", line 390, in parse_config_files
    parser.read(filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: setup.cfg
	[line  3]: 'buildouts\n'
	[line  4]: 'buildouts/*'
Bad setup.py
EGGMONKEY: Got error "Command '['mkrelease', '-qp', '-d', 'eea']' returned non-zero exit status 1" on step 3
EGGMONKEY: We were doing: #3. Run "mkrelease -qp -d eea" in package dir; (Optional) Run "python setup.py sdist upload -r eea"
[A]bort, [R]etry, [I]gnore?
</pre>

**Comment by mauritsvanrees** [comment]
Ah. :-/ 
Well, `setup.cfg` is only there to make the `check-manifest` tool not complain about a few files that are in version control but do not end up in the distribution. So it is no big loss. It has no effect on the final distribution.

**Comment by mauritsvanrees** [comment]
I see 8.8 is at http://eggrepo.eea.europa.eu/simple/ but not yet on PyPI.

**Pull request merged**
