### PR TITLE
Use select2 for the autocomplete widget

### PR DESCRIPTION
**Pull request by vincentfretin**
Instead of old jquery.autocomplete, use select2 for the autocomplete widget.
The widget now supports multi values. I added a multivalued option to the widget.

I upgraded select2 to 3.5.4 and added select2 locale files in eea.jquery too.

### CODE REVIEW

**Comment by vincentfretin** [comment]
cc @gbastien

**Comment by vincentfretin** [comment]
I just saw SolrSuggest returns {'label': s.text, 'value': s.text} that was needed for jquery.autocomplete
and now select2 needs {'id': term[0], 'text': term[1]})
What do we do? Change SolrSuggest to return id and text or keep backward compatibility and do a transformation on select2 side?

**Comment by gbastien** [comment]
Hi @vincentfretin 

the old way the widget works now was implemented recently by @sdelcourt (https://github.com/eea/eea.facetednavigation/commit/3c9a955905151beb69cc4c311b13af501ab561b1) so I think it will not be necessary (@tomgross ???)

Maybe it would be interesting to add a line about this widget and the way it works to the README.rst however...

Thank you,

Gauthier

**Comment by gbastien** [comment]
Hi @vincentfretin 

the old way the widget works now was implemented recently by @sdelcourt (https://github.com/eea/eea.facetednavigation/commit/3c9a955905151beb69cc4c311b13af501ab561b1) so I think it will not be necessary (@tomgross ???)

Maybe it would be interesting to add a line about this widget and the way it works to the README.rst however...

Thank you,

Gauthier

**Comment by avoinea** [comment]
@gbastien @vincentfretin I would like to take a look at this before merge. Is there a buildout/solr config/docker-images to start with while preparing my sandbox?

**Comment by vincentfretin** [comment]
@avoinea You can use the buildout included in the package

    cd buildouts/plone4
    python2.7 bootstrap.py
    bin/buildout -c dev.cfg

You need to install the select2 profile from eea.jquery via portal_setup.

create a facetednav, and add a autocomplete criteria with the following configuration:
- index catalog: Item Types (internal)
- autocompletion source: Types

You can search for Document, Folder or Event

**Comment by vincentfretin** [comment]
I didn't test with solr, here I use a static suggest vocabulary I wrote in eea/facetednavigation/tests/autocomplete.py

**Comment by avoinea** [comment]
JS fails with:
```
Uncaught TypeError: jQuery(...).select2 is not a function
```

Thus, please add `select2` profile as dependency with eea.facetednavigation metadata.xml and also add an upgrade step for this: see `upgrades/configure.zcml`

Thank you!

**Comment by avoinea** [comment]
I also get this error after I import select2 profile:
```
GET http://localhost:8080/Plone2/portal_css/Sunburst%20Theme/select2-spinner.gif 404 (Not Found)
```

**Comment by vincentfretin** [comment]
Ok, I'll do that now.

**Comment by vincentfretin** [comment]
@avoinea I added the upgrade step and an entry in the changelog. I have a 200 for select2-spinner.gif, the url I have is http://localhost:8080/Plone/portal_css/Sunburst%20Theme/++resource++select2/select2-spinner.gif
I'm not sure why you don't have /++resource++select2/ in your instance.

**Pull request merged**
